sonar.projectKey=sonorusau_sonorus-app
sonar.organization=sonorusau
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.config.js,**/*.config.ts,**/out/**,**/dist/**,**/build/**
sonar.coverage.exclusions=**/*
