import { Repo } from "@shared/repo/data";
import { Octokit } from "octokit";
import { readFile } from "fs-extra";
import { initGitHubClient } from "./initGitHubClient";
import { Commit, CommitFile } from "@shared/commit/data";
import { Endpoints } from "@octokit/types";
import { OctokitResponse } from "@octokit/types";
import { randomBytes } from "crypto";
import { getGitHubToken } from "./getGitHubToken";

interface Blob {
  url: string;
  sha: string;
}

interface CommitFileData {
  pathInRepo: string;
  blob: Blob;
}

type createTreeParams =
  Endpoints["POST /repos/{owner}/{repo}/git/trees"]["parameters"];

export interface AddFilesToReposRsp {
  success: boolean;
  prLinks: string[];
}

/**
 * Add files to repositories.
 * @param repos
 * @param org
 * @param filePaths
 * @returns
 */
export async function addFilesToRepos(
  repos: Repo[],
  commitFiles: CommitFile[],
  prTitle: string,
  prBody: string,
  commitMessage: string,
): Promise<AddFilesToReposRsp> {
  const rsp: AddFilesToReposRsp = {
    success: true,
    prLinks: [],
  };
  console.log("Going to use: " + (await getGitHubToken()));
  const octo = await initGitHubClient(globalThis.useEnterpriseServer);
  console.log("Using: " + (await getGitHubToken()));
  const rndPostfix: string = Math.floor(
    100000 + Math.random() * 900000,
  ).toString();
  const newBranchName: string = "add-files-" + rndPostfix;
  const prBodyNotes: string = `---
  Generated by GH Util.
  - If any change is required please update this PR.
  - If you have a suggestion please contribute back to GH Util.`;

  for (const repo of repos) {
    console.log("Add files to repo: " + repo.owner + "/" + repo.name);

    // Get default branch as base branch.
    console.log("Find repo default branch.");
    const findRepoRsp = await octo.rest.repos.get({
      owner: repo.owner,
      repo: repo.name,
    });
    const baseBranchName = findRepoRsp.data.default_branch;
    const baseBranchRsp = await octo.rest.repos.getBranch({
      owner: repo.owner,
      repo: repo.name,
      branch: baseBranchName,
    });
    console.log("Found default branch: " + baseBranchName);

    // Create new branch
    console.log("Create new branch " + newBranchName);
    const newBranchRsp = await octo.rest.git.createRef({
      owner: repo.owner,
      repo: repo.name,
      ref: "refs/heads/" + newBranchName,
      sha: baseBranchRsp.data.commit.sha,
    });

    // Get the current commit in new branch.
    console.log(
      "Get base commit in new branch SHA: " + newBranchRsp.data.object.sha,
    );
    const baseCommitRsp = await octo.rest.git.getCommit({
      owner: repo.owner,
      repo: repo.name,
      commit_sha: newBranchRsp.data.object.sha,
    });
    console.log("Got base commit SHA: " + baseCommitRsp.data.sha);

    // Load files.
    console.log("Load file blobs.");
    const commitFileDatas: CommitFileData[] = await createFileBlobs(
      octo,
      repo,
      commitFiles,
    );

    // Create tree.
    console.log("Create tree.");
    const tree = commitFileDatas.map((commitFileData: CommitFileData) => ({
      path: commitFileData.pathInRepo,
      mode: "100644",
      type: "blob",
      sha: commitFileData.blob.sha,
    })) as createTreeParams["tree"];
    const newTreeRsp = await octo.rest.git.createTree({
      owner: repo.owner,
      repo: repo.name,
      tree: tree,
      base_tree: baseCommitRsp.data.tree.sha,
    });
    console.log("Created tree: " + newTreeRsp.data.sha);

    // Create commit.
    console.log("Commit files.");
    const newCommitRsp = await octo.rest.git.createCommit({
      owner: repo.owner,
      repo: repo.name,
      message: commitMessage,
      tree: newTreeRsp.data.sha,
      parents: [baseCommitRsp.data.sha],
    });
    console.log("Created commit: " + newCommitRsp.data.sha);

    // Apply commit.
    console.log(
      "Point new branch " +
        newBranchRsp.data.ref +
        " to commit: " +
        newCommitRsp.data.sha,
    );
    const applyCommitRsp = await octo.rest.git.updateRef({
      owner: repo.owner,
      repo: repo.name,
      ref: `heads/${newBranchName}`,
      sha: newCommitRsp.data.sha,
      force: true,
    });
    console.log("New branch is pointing to commit: " + newCommitRsp.data.sha);

    // Create PR to merge new branch back to main (or master) branch.
    console.log("Create PR.");
    const newPrRsp = await octo.rest.pulls.create({
      owner: repo.owner,
      repo: repo.name,
      title: prTitle,
      head: newBranchName,
      base: baseBranchName,
      body: prBody + "\n\n" + prBodyNotes,
    });
    console.log("Created PR: " + newPrRsp.data._links.html.href);
    rsp.prLinks.push(newPrRsp.data._links.html.href);
  }

  return rsp;
}

/**
 * Load files in the provided file paths into blobs.
 * @param commitFiles
 * @returns Array of commitFileDatas. Each element contains a CommitFile
 * (the full file path & intended file path in repo) and a corresponding blob.
 */
async function createFileBlobs(
  octo: Octokit,
  repo: Repo,
  commitFiles: CommitFile[],
): Promise<CommitFileData[]> {
  const commitFileDatas: CommitFileData[] = [];
  for (const commitFile of commitFiles) {
    const fileContent = await window.api.loadFile(commitFile.fullPath);
    const createBlobRsp = await octo.rest.git.createBlob({
      owner: repo.owner,
      repo: repo.name,
      content: fileContent,
      encoding: "utf-8",
    });
    console.log("Loaded file: " + commitFile.pathInRepo);
    const commitFileData = {
      pathInRepo: commitFile.pathInRepo,
      blob: createBlobRsp.data,
    };
    commitFileDatas.push(commitFileData);
  }
  return commitFileDatas;
}
